apiVersion: v1
kind: Service               
metadata:
  name: simplepythonredisapp-service     
  namespace: python-redis
spec:         
  ports:                         
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: simplepythonredisapp           
