apiVersion: v1
kind: Service
metadata:
  name: simplepythonredisapp-serivce-metrics
  namespace: python-redis
spec:            
  ports:                 
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: simplepythonredisapp            
